# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('rush_attempts', models.IntegerField()),
                ('rush_yards', models.IntegerField()),
                ('rush_TDs', models.IntegerField()),
                ('pass_completions', models.IntegerField()),
                ('pass_yards', models.IntegerField()),
                ('pass_tds', models.IntegerField()),
            ],
        ),
    ]
