# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 23:40
from __future__ import unicode_literals
# from osu_db.models import Player
from django.db import migrations
import csv


def load_data(apps, schema_editor):
    Player = apps.get_model('osu_db', 'Player')
    csv_path = 'sports_data.csv'

    with open(csv_path, 'r') as f:
        stats = {'fieldnames': ('name', 'rush_attempts', 'rush_yards', 'rush_tds', 'pass_comps', 'pass_yards', 'pass_tds'), 'delimiter': ','}
        reader = csv.DictReader(f, **stats)
        next(reader, None)

    for row in reader:
        p = Player(**row)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osu_db', '0001_initial'),
    ]

    operations = [
    ]
